### ISSUE TITLE
mysql remote connection issue

### ISSUE THREAD

**Issue by sachi842** [mattrayner/docker-lamp#20]
I am trying to expose 3306 to my Docker host via: -p "3306:3306". I cannot connect to 3306 from outside the container.
Someone on the Docker Slack community helped, and it looks like MySQL is bound to 127.0.0.1:3306 inside the container, not 0.0.0.0:3306.
Can you take a look?

root@117903e45f7f:/# apt install net-tools && netstat -lnp | grep 3306
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  net-tools
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 175 kB of archives.
After this operation, 725 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu xenial/main amd64 net-tools amd64 1.60-26ubuntu1 [175 kB]
Fetched 175 kB in 0s (202 kB/s)   
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package net-tools.
(Reading database ... 17375 files and directories currently installed.)
Preparing to unpack .../net-tools_1.60-26ubuntu1_amd64.deb ...
Unpacking net-tools (1.60-26ubuntu1) ...
Setting up net-tools (1.60-26ubuntu1) ...
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      -

**Comment by mattrayner** [comment]
sure, I'll try and take a look at this today for you :+1:

**Comment by sachi842** [comment]
Thank you for helping me

**Comment by sachi842** [comment]
Hello Matt,

Were you able to check what is not working well?

**Comment by Ali-Kiyan** [comment]
@sachi842 @mattrayner I am having the same problem. I cannot access the mysql database from outside the container. I mapped the port 3306 to 3050.

**Comment by mattrayner** [comment]
I'm going to have another look at this now

**Comment by Ali-Kiyan** [comment]
I found a solution for MySQL remote access outside of the container. edit MySQL config file under etc and change the binding address to 0.0.0.0 and then restart MySQL. finally, restart the LAMP container.

**Comment by mattrayner** [comment]
I've added this to the Dockerfiles and am testing now:

```  # Allow mysql to bind on 0.0.0.0
RUN sed -i "s/.*bind-address.*/bind-address = 0.0.0.0/" /etc/mysql/my.cnf```

**Comment by mattrayner** [comment]
Fixed in #36

**Comment by tangruize** [comment]
I found it still does not work. Maybe the the file name `
/etc/mysql/my.cnf' changed to `/etc/mysql/mysql.conf.d/mysqld.cnf'?

**Comment by Ali-Kiyan** [comment]
Try this:
`sed -i "s/.*bind-address.*/bind-address = 0.0.0.0/" /etc/mysql/mysql.conf.d/mysqld.cnf`

**Comment by tangruize** [comment]
Sorry, I'm new to docker. I tried docker commit to save changes, however it doesn't work. Could you update the image?

**Comment by doron-mil** [comment]
I'm running the latest-1804.
I still has problem as described.
Help, anyone?

**Comment by freeyland** [comment]
Same issue

**Comment by pzhlkj6612** [comment]
See it #63 , a temporary solution.

**Comment by doron-mil** [comment]
@pzhlkj6612   : 
didn't work for me. And I don't see any changes in the mysql logs when trying to connect.
I see it only when connecting via the http://localhost/phpmyadmin/index.php

**Comment by freeyland** [comment]
Thanx also working for me now

**Comment by mattrayner** [comment]
I'm adding the fix here to the Dockerfile for 1604 and 1804 - once I've got a fix I'll post it here

**Comment by mattrayner** [comment]
This should now be fixed in the latest release

Thanks for all your patience, if you can confirm and post back that would be amazing!

**Comment by freeyland** [comment]
Hi, it is working now
